package cunori.kardex.views;

import cunori.kardex.controller.ClienteJpaController;
import cunori.kardex.dao.Cliente;
import cunori.kardex.encrypt.Hash;
import java.awt.Font;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Diego Ramos
 * @author Hermas Ramirez
 */
public class FormCrearCompra extends javax.swing.JFrame {

    //EntityManagerFactory emf;
    //ClienteJpaController ClienteEntityManager;
    //public static TableRowSorter<DefaultTableModel> sorter;

    public FormCrearCompra() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/logo.png")).getImage());
        //this.setExtendedState(MAXIMIZED_BOTH);

       // emf = Persistence.createEntityManagerFactory("cunori_kardex_jar_1.0-SNAPSHOTPU");
       // ClienteEntityManager = new ClienteJpaController(emf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCodin = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        lblCodin1 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblCodin2 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        lblCodin3 = new javax.swing.JLabel();
        lblCodin4 = new javax.swing.JLabel();
        txtNumCompra = new javax.swing.JTextField();
        lblCodin5 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        txtNIT = new javax.swing.JTextField();
        lblCodin8 = new javax.swing.JLabel();
        lblCodin6 = new javax.swing.JLabel();
        txtFechaCompra = new javax.swing.JTextField();
        lblCodin7 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        pnlLeft = new javax.swing.JPanel();
        btnImprimir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(129, 164, 220));
        jPanel1.setPreferredSize(new java.awt.Dimension(931, 522));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Datos de la Compra");

        lblCodin.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblCodin.setForeground(new java.awt.Color(0, 0, 0));
        lblCodin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodin.setText("NIT del Proveedor:");

        txtNombreP.setBackground(new java.awt.Color(129, 164, 220));
        txtNombreP.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtNombreP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));

        lblCodin1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblCodin1.setForeground(new java.awt.Color(0, 0, 0));
        lblCodin1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodin1.setText("Número de Compra:");

        txtDireccion.setBackground(new java.awt.Color(129, 164, 220));
        txtDireccion.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtDireccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        lblCodin2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblCodin2.setForeground(new java.awt.Color(0, 0, 0));
        lblCodin2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodin2.setText("Nombre del Producto:");

        txtTelefono.setBackground(new java.awt.Color(129, 164, 220));
        txtTelefono.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));

        txtCorreo.setBackground(new java.awt.Color(129, 164, 220));
        txtCorreo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtCorreo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));

        lblCodin3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblCodin3.setForeground(new java.awt.Color(0, 0, 0));
        lblCodin3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodin3.setText("Direccion:");

        lblCodin4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblCodin4.setForeground(new java.awt.Color(0, 0, 0));
        lblCodin4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodin4.setText("Correo:");

        txtNumCompra.setBackground(new java.awt.Color(129, 164, 220));
        txtNumCompra.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtNumCompra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));

        lblCodin5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblCodin5.setForeground(new java.awt.Color(0, 0, 0));
        lblCodin5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodin5.setText("Telefono:");

        txtNombreProducto.setBackground(new java.awt.Color(129, 164, 220));
        txtNombreProducto.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtNombreProducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));

        txtNIT.setBackground(new java.awt.Color(129, 164, 220));
        txtNIT.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtNIT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));

        lblCodin8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblCodin8.setForeground(new java.awt.Color(0, 0, 0));
        lblCodin8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodin8.setText("Nombre del Proveedor:");

        lblCodin6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblCodin6.setForeground(new java.awt.Color(0, 0, 0));
        lblCodin6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodin6.setText("Fecha de la Compra:");

        txtFechaCompra.setBackground(new java.awt.Color(129, 164, 220));
        txtFechaCompra.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtFechaCompra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));

        lblCodin7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblCodin7.setForeground(new java.awt.Color(0, 0, 0));
        lblCodin7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodin7.setText("Total:");

        txtTotal.setBackground(new java.awt.Color(129, 164, 220));
        txtTotal.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                            .addComponent(txtDireccion)
                            .addComponent(txtNIT)
                            .addComponent(lblCodin)
                            .addComponent(lblCodin3)
                            .addComponent(lblCodin4)
                            .addComponent(lblCodin2)
                            .addComponent(txtNombreProducto)
                            .addComponent(lblCodin7)
                            .addComponent(txtTotal))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCodin1)
                            .addComponent(lblCodin8)
                            .addComponent(txtNombreP, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                            .addComponent(lblCodin5)
                            .addComponent(txtTelefono)
                            .addComponent(txtNumCompra)
                            .addComponent(lblCodin6)
                            .addComponent(txtFechaCompra))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCodin8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodin3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCodin5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodin4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCodin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCodin6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(lblCodin7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(326, 326, 326))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 0, 1060, 590));

        pnlLeft.setBackground(new java.awt.Color(129, 164, 220));

        btnImprimir.setBackground(new java.awt.Color(129, 164, 220));
        btnImprimir.setToolTipText("Imprimir");
        btnImprimir.setBorder(null);
        btnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(129, 164, 220));
        btnEliminar.setToolTipText("Anular");
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(129, 164, 220));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guardarCheque.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setBorder(null);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(129, 164, 220));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regresar.png"))); // NOI18N
        btnRegresar.setToolTipText("Guardar");
        btnRegresar.setBorder(null);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar)
                    .addComponent(btnImprimir)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeftLayout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addComponent(btnImprimir)
                .addGap(214, 214, 214)
                .addComponent(btnEliminar)
                .addGap(62, 62, 62)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addGap(20, 20, 20))
        );

        getContentPane().add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       /* if (CrearCliente()) {
            JOptionPane.showMessageDialog(null, "El Cliente " + txtDireccion.getText() + " "+ txtTelefono.getText() +" se creó correctamente");
            ListarClientes lc = new ListarClientes();
            lc.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo crear el Cliente");
        }*/

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Inicio in = new Inicio();
        in.setVisible(true);
        this.dispose();
        //commit
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed
/*
    private Boolean CrearCliente() {
        if (!Vacio()) {
            String id = UUID.randomUUID().toString();
            Cliente p = new Cliente();
            p.setId(id);
            p.setDpi(txtNombreP.getText());
            p.setNit(txtNIT.getText());
            p.setNombre(txtDireccion.getText());
            p.setApellidos(txtTelefono.getText());
            p.setDireccion(txtCorreo.getText());
            p.setCorreo(txtNumCompra.getText());
            p.setTelefono(txtNombreProducto.getText());
            
            try {
                ClienteEntityManager.create(p);
                return true;
            } catch (Exception ex) {
//            Logger.getLogger(FormUsuario.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Datos repetidos o mal ingresados");
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Faltan campos por llenar");
        }
        return false;
    }

    private Boolean Vacio() {
        return txtNombreP.getText().isEmpty() && txtNIT.getText().isEmpty() && txtDireccion.getText().isEmpty()
                && txtTelefono.getText().isEmpty() && txtCorreo.getText().isEmpty() 
                && txtNumCompra.getText().isEmpty() && txtNombreProducto.getText().isEmpty();
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCrearCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCrearCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCrearCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCrearCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCrearCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodin;
    private javax.swing.JLabel lblCodin1;
    private javax.swing.JLabel lblCodin2;
    private javax.swing.JLabel lblCodin3;
    private javax.swing.JLabel lblCodin4;
    private javax.swing.JLabel lblCodin5;
    private javax.swing.JLabel lblCodin6;
    private javax.swing.JLabel lblCodin7;
    private javax.swing.JLabel lblCodin8;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaCompra;
    private javax.swing.JTextField txtNIT;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtNumCompra;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
