package cunori.kardex.views;

import cunori.kardex.auxiliar.FacturaReport;
import cunori.kardex.controller.ClienteJpaController;
import cunori.kardex.controller.CompraJpaController;
import cunori.kardex.controller.DetalleCompraJpaController;
import cunori.kardex.controller.DetalleVentaJpaController;
import cunori.kardex.controller.FacturaCompraJpaController;
import cunori.kardex.controller.FacturaVentaJpaController;
import cunori.kardex.controller.ProductoJpaController;
import cunori.kardex.controller.ProveedorJpaController;
import cunori.kardex.controller.UsuarioJpaController;
import cunori.kardex.controller.VentaJpaController;
import cunori.kardex.dao.Cliente;
import cunori.kardex.dao.Venta;
import cunori.kardex.dao.DetalleCompra;
import cunori.kardex.dao.DetalleVenta;
import cunori.kardex.dao.FacturaCompra;
import cunori.kardex.dao.FacturaVenta;
import cunori.kardex.dao.LibroVenta;
import cunori.kardex.dao.PojoFactura;
import cunori.kardex.dao.Producto;
import cunori.kardex.dao.Proveedor;
import cunori.kardex.dao.Usuario;

import cunori.kardex.encrypt.Hash;
import static cunori.kardex.views.FormCrearCompra.txtTotalPagar;

import static cunori.kardex.views.Inicio.lblBienvenida;
import java.awt.Color;
import java.awt.Font;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Diego Ramos
 * @author Hermas Ramirez
 */
public class FormCrearVenta extends javax.swing.JFrame {

    EntityManagerFactory emf;
    FacturaVentaJpaController FacturaVentaEntityManager;
    ClienteJpaController ClienteEntityManager;
    UsuarioJpaController UsuarioEntityManager;
    VentaJpaController VentaEntityManager;
    DetalleVentaJpaController DetalleVentaEntityManager;
    ProductoJpaController ProductoEntityManager;

    public static String idCliente = "";
    String idVenta = "";
    public static Double TotalVenta = 0.0;
    Boolean banderaDescuento = true;
    Double cambio = 0.0;
    String noDoc = "";

    //public static TableRowSorter<DefaultTableModel> sorter;
    public FormCrearVenta() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/logo.png")).getImage());
        //this.setExtendedState(MAXIMIZED_BOTH);
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        model.setRowCount(0); //eliminar filas existentes
        emf = Persistence.createEntityManagerFactory("cunori_kardex_jar_1.0-SNAPSHOTPU");
        FacturaVentaEntityManager = new FacturaVentaJpaController(emf);
        ClienteEntityManager = new ClienteJpaController(emf);
        UsuarioEntityManager = new UsuarioJpaController(emf);
        VentaEntityManager = new VentaJpaController(emf);
        DetalleVentaEntityManager = new DetalleVentaJpaController(emf);
        ProductoEntityManager = new ProductoJpaController(emf);

        InicioSesion();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlProductos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnSeleccionarProd = new javax.swing.JButton();
        lblDescuento = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        lblTotalPagar = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        btnEliminarFila = new javax.swing.JButton();
        btnAplicarDescuento = new javax.swing.JButton();
        lblPaga = new javax.swing.JLabel();
        txtPaga = new javax.swing.JTextField();
        lblCambio = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();
        pnlLeft = new javax.swing.JPanel();
        btnCrearCompra = new javax.swing.JButton();
        btnCancelarCompra = new javax.swing.JButton();
        btnRegresarCompra = new javax.swing.JButton();
        jPnlFactura = new javax.swing.JPanel();
        lblNoSerie = new javax.swing.JLabel();
        txtNoSerie = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        txtFechaRegistro = new javax.swing.JTextField();
        lblFechaRegistro = new javax.swing.JLabel();
        jPnlUsuario = new javax.swing.JPanel();
        lblNITUsuario = new javax.swing.JLabel();
        txtNITUsuario = new javax.swing.JTextField();
        lblNombreUsuario = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jPnlProveedor = new javax.swing.JPanel();
        lblNITCliente = new javax.swing.JLabel();
        txtNITCliente = new javax.swing.JTextField();
        lblNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        btnAgregarProv = new javax.swing.JButton();
        btnSeleccionarProv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnlProductos.setBackground(new java.awt.Color(129, 164, 220));
        jPnlProductos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N
        jPnlProductos.setPreferredSize(new java.awt.Dimension(931, 522));

        tblProductos.setBackground(new java.awt.Color(204, 204, 204));
        tblProductos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 102, 255)));
        tblProductos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tblProductos.setForeground(new java.awt.Color(0, 0, 0));
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Categoria", "Marca", "Unidad", "Peso Neto", "Precio Compra", "Precio Venta", "Stock", "Cantidad", "Total Compra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblProductos.setGridColor(new java.awt.Color(0, 0, 0));
        tblProductos.setSelectionBackground(new java.awt.Color(255, 255, 204));
        tblProductos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblProductos.setShowGrid(true);
        tblProductos.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setPreferredWidth(150);
            tblProductos.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblProductos.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblProductos.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblProductos.getColumnModel().getColumn(4).setPreferredWidth(150);
            tblProductos.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblProductos.getColumnModel().getColumn(6).setPreferredWidth(150);
            tblProductos.getColumnModel().getColumn(7).setPreferredWidth(150);
            tblProductos.getColumnModel().getColumn(8).setPreferredWidth(100);
            tblProductos.getColumnModel().getColumn(9).setPreferredWidth(100);
        }

        btnSeleccionarProd.setBackground(new java.awt.Color(129, 164, 220));
        btnSeleccionarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0select_110958.png"))); // NOI18N
        btnSeleccionarProd.setToolTipText("Seleccionar");
        btnSeleccionarProd.setBorder(null);
        btnSeleccionarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeleccionarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarProdActionPerformed(evt);
            }
        });

        lblDescuento.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblDescuento.setForeground(new java.awt.Color(0, 0, 0));
        lblDescuento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDescuento.setText("Descuento:");

        txtDescuento.setBackground(new java.awt.Color(129, 164, 220));
        txtDescuento.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtDescuento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));
        txtDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescuentoKeyReleased(evt);
            }
        });

        lblTotalPagar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTotalPagar.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalPagar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalPagar.setText("Total a pagar:");

        txtTotalPagar.setEditable(false);
        txtTotalPagar.setBackground(new java.awt.Color(129, 164, 220));
        txtTotalPagar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTotalPagar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));

        btnEliminarFila.setBackground(new java.awt.Color(129, 164, 220));
        btnEliminarFila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delFila.png"))); // NOI18N
        btnEliminarFila.setToolTipText("Eliminar");
        btnEliminarFila.setBorder(null);
        btnEliminarFila.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFilaActionPerformed(evt);
            }
        });

        btnAplicarDescuento.setBackground(new java.awt.Color(129, 164, 220));
        btnAplicarDescuento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/31-check-solid.gif"))); // NOI18N
        btnAplicarDescuento.setToolTipText("Seleccionar");
        btnAplicarDescuento.setBorder(null);
        btnAplicarDescuento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAplicarDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarDescuentoActionPerformed(evt);
            }
        });

        lblPaga.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblPaga.setForeground(new java.awt.Color(0, 0, 0));
        lblPaga.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPaga.setText("Paga con:");

        txtPaga.setBackground(new java.awt.Color(129, 164, 220));
        txtPaga.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtPaga.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));
        txtPaga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPagaKeyReleased(evt);
            }
        });

        lblCambio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblCambio.setForeground(new java.awt.Color(0, 0, 0));
        lblCambio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCambio.setText("Cambio:");

        txtCambio.setEditable(false);
        txtCambio.setBackground(new java.awt.Color(129, 164, 220));
        txtCambio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtCambio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));
        txtCambio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCambioKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPnlProductosLayout = new javax.swing.GroupLayout(jPnlProductos);
        jPnlProductos.setLayout(jPnlProductosLayout);
        jPnlProductosLayout.setHorizontalGroup(
            jPnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlProductosLayout.createSequentialGroup()
                .addGroup(jPnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlProductosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSeleccionarProd)
                            .addComponent(btnEliminarFila))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1111, Short.MAX_VALUE))
                    .addGroup(jPnlProductosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDescuento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAplicarDescuento)
                        .addGap(15, 15, 15)
                        .addComponent(lblTotalPagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblPaga)
                        .addGap(18, 18, 18)
                        .addComponent(txtPaga, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lblCambio)
                        .addGap(18, 18, 18)
                        .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        jPnlProductosLayout.setVerticalGroup(
            jPnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlProductosLayout.createSequentialGroup()
                        .addComponent(btnSeleccionarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(btnEliminarFila, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAplicarDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPaga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPnlProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pnlLeft.setBackground(new java.awt.Color(129, 164, 220));

        btnCrearCompra.setBackground(new java.awt.Color(129, 164, 220));
        btnCrearCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0shopping-cart-add-button_icon-icons.com_56132.png"))); // NOI18N
        btnCrearCompra.setToolTipText("Crear Compra");
        btnCrearCompra.setBorder(null);
        btnCrearCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCompraActionPerformed(evt);
            }
        });

        btnCancelarCompra.setBackground(new java.awt.Color(129, 164, 220));
        btnCancelarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0shopping-cart-cancel-button_icon-icons.com_56130.png"))); // NOI18N
        btnCancelarCompra.setToolTipText(" Cancelar Compra");
        btnCancelarCompra.setBorder(null);
        btnCancelarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCompraActionPerformed(evt);
            }
        });

        btnRegresarCompra.setBackground(new java.awt.Color(129, 164, 220));
        btnRegresarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0undo_111005.png"))); // NOI18N
        btnRegresarCompra.setToolTipText("Regresar");
        btnRegresarCompra.setBorder(null);
        btnRegresarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeftLayout.createSequentialGroup()
                .addContainerGap(508, Short.MAX_VALUE)
                .addComponent(btnCrearCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelarCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresarCompra)
                .addGap(20, 20, 20))
        );

        jPnlFactura.setBackground(new java.awt.Color(129, 164, 220));
        jPnlFactura.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N
        jPnlFactura.setPreferredSize(new java.awt.Dimension(931, 522));

        lblNoSerie.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblNoSerie.setForeground(new java.awt.Color(0, 0, 0));
        lblNoSerie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNoSerie.setText("No. Serie:");

        txtNoSerie.setBackground(new java.awt.Color(129, 164, 220));
        txtNoSerie.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtNoSerie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));

        lblTipo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(0, 0, 0));
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipo.setText("Tipo:");

        cbxTipo.setBackground(new java.awt.Color(129, 164, 220));
        cbxTipo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo 1", "Tipo 2", "Tipo 3" }));

        txtFechaRegistro.setBackground(new java.awt.Color(129, 164, 220));
        txtFechaRegistro.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtFechaRegistro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));
        txtFechaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaRegistroActionPerformed(evt);
            }
        });

        lblFechaRegistro.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblFechaRegistro.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaRegistro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaRegistro.setText("Fecha de Registro:");

        javax.swing.GroupLayout jPnlFacturaLayout = new javax.swing.GroupLayout(jPnlFactura);
        jPnlFactura.setLayout(jPnlFacturaLayout);
        jPnlFacturaLayout.setHorizontalGroup(
            jPnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNoSerie)
                    .addComponent(txtNoSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipo)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaRegistro)
                    .addComponent(txtFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlFacturaLayout.setVerticalGroup(
            jPnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlFacturaLayout.createSequentialGroup()
                .addGroup(jPnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlFacturaLayout.createSequentialGroup()
                .addContainerGap(3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblNoSerie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNoSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPnlUsuario.setBackground(new java.awt.Color(129, 164, 220));
        jPnlUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N
        jPnlUsuario.setPreferredSize(new java.awt.Dimension(931, 522));

        lblNITUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblNITUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblNITUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNITUsuario.setText("NIT del Usuario:");

        txtNITUsuario.setEditable(false);
        txtNITUsuario.setBackground(new java.awt.Color(129, 164, 220));
        txtNITUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtNITUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));

        lblNombreUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreUsuario.setText("Nombre del Usuario:");

        txtNombreUsuario.setEditable(false);
        txtNombreUsuario.setBackground(new java.awt.Color(129, 164, 220));
        txtNombreUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtNombreUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));

        javax.swing.GroupLayout jPnlUsuarioLayout = new javax.swing.GroupLayout(jPnlUsuario);
        jPnlUsuario.setLayout(jPnlUsuarioLayout);
        jPnlUsuarioLayout.setHorizontalGroup(
            jPnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlUsuarioLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(jPnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNITUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNITUsuario))
                .addGap(32, 32, 32)
                .addGroup(jPnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreUsuario)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPnlUsuarioLayout.setVerticalGroup(
            jPnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlUsuarioLayout.createSequentialGroup()
                .addGroup(jPnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNITUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNITUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPnlProveedor.setBackground(new java.awt.Color(129, 164, 220));
        jPnlProveedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 24))); // NOI18N
        jPnlProveedor.setPreferredSize(new java.awt.Dimension(931, 522));

        lblNITCliente.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblNITCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblNITCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNITCliente.setText("NIT del Cliente:");

        txtNITCliente.setEditable(false);
        txtNITCliente.setBackground(new java.awt.Color(129, 164, 220));
        txtNITCliente.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtNITCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));
        txtNITCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNITClienteActionPerformed(evt);
            }
        });

        lblNombreCliente.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblNombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreCliente.setText("Nombre del Cliente:");

        txtNombreCliente.setEditable(false);
        txtNombreCliente.setBackground(new java.awt.Color(129, 164, 220));
        txtNombreCliente.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtNombreCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 153, 255)));

        btnAgregarProv.setBackground(new java.awt.Color(129, 164, 220));
        btnAgregarProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0personadd_111023.png"))); // NOI18N
        btnAgregarProv.setToolTipText("Agregar");
        btnAgregarProv.setBorder(null);
        btnAgregarProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProvActionPerformed(evt);
            }
        });

        btnSeleccionarProv.setBackground(new java.awt.Color(129, 164, 220));
        btnSeleccionarProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0personselect_110958.png"))); // NOI18N
        btnSeleccionarProv.setToolTipText("Seleccionar");
        btnSeleccionarProv.setBorder(null);
        btnSeleccionarProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeleccionarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarProvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlProveedorLayout = new javax.swing.GroupLayout(jPnlProveedor);
        jPnlProveedor.setLayout(jPnlProveedorLayout);
        jPnlProveedorLayout.setHorizontalGroup(
            jPnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarProv)
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionarProv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNITCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNITCliente))
                .addGap(32, 32, 32)
                .addGroup(jPnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCliente)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlProveedorLayout.setVerticalGroup(
            jPnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlProveedorLayout.createSequentialGroup()
                .addGroup(jPnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlProveedorLayout.createSequentialGroup()
                        .addGroup(jPnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarProv)
                            .addComponent(btnSeleccionarProv))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPnlProveedorLayout.createSequentialGroup()
                        .addGroup(jPnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNITCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnlProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNITCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnlFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 1236, Short.MAX_VALUE)
                    .addComponent(jPnlProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 1236, Short.MAX_VALUE)
                    .addComponent(jPnlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 1236, Short.MAX_VALUE)
                    .addComponent(jPnlProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 1236, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnlFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPnlProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPnlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPnlProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCompraActionPerformed
        if (!Vacio()) {
            DatosFactura();//seteando datos factura
            Venta();//seteando datos de la venta
            DatosDetalleVenta();//seteando datos detalleVenta
            JOptionPane.showMessageDialog(null, "La Venta se creó correctamente");
            Imprimir();
            //limpiar();
//            FormCrearVenta fcc = new FormCrearVenta();
//            fcc.setVisible(true);
//            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Campos vacios, no se pudo crear la venta");
        }
    }//GEN-LAST:event_btnCrearCompraActionPerformed

    private void btnRegresarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarCompraActionPerformed
        Inicio in = new Inicio();
        in.setVisible(true);
        this.dispose();
        //commit
    }//GEN-LAST:event_btnRegresarCompraActionPerformed

    private void btnSeleccionarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarProdActionPerformed
        ListarProductoVenta lpv = new ListarProductoVenta(this, true);
        lpv.setVisible(true);
    }//GEN-LAST:event_btnSeleccionarProdActionPerformed

    private void btnAgregarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProvActionPerformed
        FormCrearClienteVenta fcv = new FormCrearClienteVenta(this, true);
        fcv.setVisible(true);
    }//GEN-LAST:event_btnAgregarProvActionPerformed

    private void btnSeleccionarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarProvActionPerformed
        ListarClientesVenta lcv = new ListarClientesVenta(this, true);
        lcv.setVisible(true);
    }//GEN-LAST:event_btnSeleccionarProvActionPerformed

    private void btnCancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCompraActionPerformed
        limpiar();
        JOptionPane.showMessageDialog(null, "La venta se ha cancelado");
    }//GEN-LAST:event_btnCancelarCompraActionPerformed

    private void btnEliminarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFilaActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        //model.removeRow(tblProductos.getSelectedRow());

        int fila = tblProductos.getSelectedRow();
        if (fila != -1) {
            Double cantEliminada = Double.valueOf(tblProductos.getValueAt(fila, 10).toString());
            TotalVenta = Double.valueOf(txtTotalPagar.getText());
            TotalVenta = TotalVenta - cantEliminada;
            txtTotalPagar.setText(TotalVenta.toString());
            TotalVenta = 0.0;
            model.removeRow(tblProductos.getSelectedRow());
            JOptionPane.showMessageDialog(null, "El Producto se ha eliminado de la Venta");
        } else {
            JOptionPane.showMessageDialog(null, "No se ha selccionado ningun Producto");
        }
    }//GEN-LAST:event_btnEliminarFilaActionPerformed

    private void txtDescuentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescuentoKeyReleased
//        Double totalP = Double.valueOf(txtTotalPagar.getText());
//        if(!txtDescuento.getText().isEmpty()){
//        Double totalR = totalP-Double.valueOf(txtDescuento.getText());
//        txtTotalPagar.setText(totalR.toString());
//        }

    }//GEN-LAST:event_txtDescuentoKeyReleased

    private void btnAplicarDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarDescuentoActionPerformed
        Double totalP = Double.valueOf(txtTotalPagar.getText());
        if (!txtDescuento.getText().isEmpty() && banderaDescuento) {
            Double totalR = totalP - Double.valueOf(txtDescuento.getText());
            txtTotalPagar.setText(totalR.toString());
            txtDescuento.setEditable(false);
            banderaDescuento = false;
        }
    }//GEN-LAST:event_btnAplicarDescuentoActionPerformed

    private void txtFechaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaRegistroActionPerformed

    private void txtNITClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNITClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNITClienteActionPerformed

    private void txtCambioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCambioKeyReleased

    }//GEN-LAST:event_txtCambioKeyReleased

    private void txtPagaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagaKeyReleased
        if (!txtPaga.getText().isEmpty() && !txtPaga.getText().isBlank()) {
            Double pag = Double.valueOf(txtPaga.getText());
            Double totPag = Double.valueOf(txtTotalPagar.getText());
            if (pag >= totPag) {
                txtPaga.setCaretColor(Color.BLACK);
                txtPaga.setForeground(Color.BLACK);
                cambio = Double.valueOf(txtPaga.getText()) - Double.valueOf(txtTotalPagar.getText());
                txtCambio.setText(cambio.toString());
            } else {
                txtPaga.setCaretColor(Color.red);
                txtPaga.setForeground(Color.red);
                txtCambio.setText("");
            }
        }
    }//GEN-LAST:event_txtPagaKeyReleased

    private Boolean Vacio() {
        return txtNoSerie.getText().isEmpty() && txtFechaRegistro.getText().isEmpty() && txtNITCliente.getText().isEmpty()
                && txtNombreCliente.getText().isEmpty() && txtNITUsuario.getText().isEmpty() && txtNombreUsuario.getText().isEmpty()
                && txtDescuento.getText().isEmpty() && txtTotalPagar.getText().isEmpty() && tblProductos.getRowCount() == 0;
    }

    public void InicioSesion() {
        System.out.println("id usuario desde compra inicio" + Inicio.SesionUsuario);
        Usuario u = UsuarioEntityManager.findUsuario(Inicio.SesionUsuario);
        txtNITUsuario.setText(u.getNit());
        txtNombreUsuario.setText(u.getNombre());
    }

    private void DatosFactura() {
        FacturaVenta fv = new FacturaVenta();

        fv.setNoSerie(txtNoSerie.getText());
        noDoc = UUID.randomUUID().toString();
        fv.setNoDocumento(noDoc);

        Integer opTipo = cbxTipo.getSelectedIndex() + 1;
        fv.setTipo(opTipo.toString());
        fv.setNombreNegocio("Mini Despensa Olopa");
        fv.setDireccionNegocio("1ra Calle 3-58 Zona 1, Olopa-Chiquimula");
        fv.setTelefonoNegocio("44632548");
        try {
            //seteando la fecha
            Date dt = new SimpleDateFormat("dd/MM/yyyy")
                    .parse(txtFechaRegistro.getText());
            fv.setFechaEmision(dt);
        } catch (ParseException ex) {
            //Logger.getLogger(CrearFactura.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Fecha mal ingresada");
        }
        BigDecimal descuento = new BigDecimal(txtDescuento.getText());
        fv.setDescuento(descuento);

        try {
            FacturaVentaEntityManager.create(fv);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se pudo crear la factura");
            Logger.getLogger(FormCrearVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void DatosCliente(String id, String nitCliente, String nombreCliente) {
        idCliente = id;
        txtNITCliente.setText(nitCliente);
        txtNombreCliente.setText(nombreCliente);
    }

    public static void DatosProducto(String codigo, String nombre, String categoria, String marca, String unidad, String pesoNeto, Double precioCompra, Double precioVenta, Integer stock, Integer cantidad) {
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();

        //model.setRowCount(0); //eliminar filas existentes
        tblProductos.setDefaultRenderer(Object.class, new Render());
        Object newRow[] = {codigo, nombre, categoria, marca, unidad, pesoNeto, precioCompra, precioVenta, stock, cantidad, precioVenta * cantidad};
        model.addRow(newRow);

        for (int i = 0; i < tblProductos.getRowCount(); i++) {
            TotalVenta += Double.parseDouble(tblProductos.getValueAt(i, 10).toString());
        }
        txtTotalPagar.setText(TotalVenta.toString());
        TotalVenta = 0.0;
    }

    private void Venta() {
        Integer cant = 0;
        Double total = 0.0;
        Venta v = new Venta();
        FacturaVenta fv = new FacturaVenta();
        Usuario u = new Usuario();
        Cliente cli = new Cliente();
        LibroVenta lv = new LibroVenta();
        lv.setId("L1"); //por defecto se estaran agregando al libro de ventas 1
        cli.setId(idCliente);
        u.setId(Inicio.SesionUsuario);
        fv.setNoSerie(txtNoSerie.getText());

        String id = UUID.randomUUID().toString();
        idVenta = id;
        v.setId(id);
        v.setIdFactura(fv);
        v.setIdLibroVenta(lv);
        v.setIdUsuario(u);
        v.setIdCliente(cli);
        //seteando Fecha
        try {
            //seteando la fecha
            Date dt = new SimpleDateFormat("dd/MM/yyyy")
                    .parse(txtFechaRegistro.getText());
            v.setFechaVenta(dt);
        } catch (ParseException ex) {
            //Logger.getLogger(CrearFactura.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Fecha mal ingresada");
        }
        for (int i = 0; i < tblProductos.getRowCount(); i++) {
            cant += Integer.valueOf(tblProductos.getValueAt(i, 9).toString());
            total += Double.valueOf(tblProductos.getValueAt(i, 10).toString());
        }
        v.setCantProducto(cant);
        Double desc = Double.valueOf(txtDescuento.getText());
        BigDecimal TotalCompra = new BigDecimal(total - desc);
        v.setTotal(TotalCompra);
        System.out.println("este es el Total de la Compra " + TotalCompra);
//        Double paga = Double.valueOf(txtPaga.getText());
//        Double cambio = Double.valueOf(txtCambio.getText());
//        cambio = paga-total;
//        if(paga>total){
//            BigDecimal DevCambio = new BigDecimal(cambio);
//            v.setTotal(DevCambio);
//        }else{
//            JOptionPane.showMessageDialog(null, "El Pago es menor que el Total de la Venta");
//        }

        try {
            VentaEntityManager.create(v);
        } catch (Exception ex) {
            Logger.getLogger(FormCrearVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void DatosDetalleVenta() {
        Producto p = new Producto();

        for (int i = 0; i < tblProductos.getRowCount(); i++) {
            String codigo = tblProductos.getValueAt(i, 0).toString();
//            p.setNombre(tblProductos.getValueAt(i, 1).toString());
//            p.setCategoria(tblProductos.getValueAt(i, 2).toString());
//            p.setMarca(tblProductos.getValueAt(i, 3).toString());
//            p.setUnidad(tblProductos.getValueAt(i, 4).toString());
//            p.setPesoNeto(tblProductos.getValueAt(i, 5).toString());
//            Integer stock = Integer.valueOf(tblProductos.getValueAt(i, 8).toString());
//            BigDecimal precioCompra = new BigDecimal(tblProductos.getValueAt(i, 6).toString());
            BigDecimal precioVenta = new BigDecimal(tblProductos.getValueAt(i, 7).toString());
            p.setCodigo(codigo);
//            p.setStock(stock);
//            p.setPrecioCompra(precioCompra);
            p.setPrecioVenta(precioVenta);
//            try {
//                ProductoEntityManager.edit(p);
//            } catch (Exception ex) {
//                JOptionPane.showMessageDialog(null, "No se actualizar el producto");
//                Logger.getLogger(FormCrearVenta.class.getName()).log(Level.SEVERE, null, ex);
//            }
            //Seteando datos detalle compra 
            DetalleVenta dv = new DetalleVenta();
            Venta v = new Venta();
            v.setId(idVenta);
            String id = UUID.randomUUID().toString();
            dv.setId(id);
            dv.setIdVenta(v);
            dv.setCodigoProducto(p);
            dv.setCantidad(Integer.parseInt(tblProductos.getValueAt(i, 9).toString()));
            BigDecimal totalIndividual = new BigDecimal(Double.parseDouble(p.getPrecioVenta().toString()) * dv.getCantidad());
            dv.setTotal(totalIndividual);

            try {
                DetalleVentaEntityManager.create(dv);
            } catch (Exception ex) {
                Logger.getLogger(FormCrearVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    private void Imprimir() {
        int fila = tblProductos.getSelectedRow();
        FacturaVenta fv = new FacturaVenta();
        FacturaReport.NombreNegocio = "Mini Despensa Olopa";
        FacturaReport.NoSerie = txtNoSerie.getText();
        FacturaReport.NoDocumento = noDoc;
        SimpleDateFormat sdf2 = new SimpleDateFormat("dd/MM/YYYY");
        FacturaReport.Fecha = txtFechaRegistro.getText();
        Integer opTipo = cbxTipo.getSelectedIndex() + 1;
        FacturaReport.Tipo = opTipo.toString();
        FacturaReport.Telefono = "44632548";

        Object[][] listadoFactura;

        int cantRow = tblProductos.getRowCount();

        try {

            JasperReport report = (JasperReport) JRLoader.loadObject(getClass().getResource("/factura.jasper"));
            JasperPrint jprint = JasperFillManager.fillReport(report, null, FacturaReport.getDataSource());

            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            view.setVisible(true);

        } catch (JRException ex) {
            ex.getMessage();
        }

    }

    public static ArrayList<PojoFactura> detalleVenta() {
        ArrayList<PojoFactura> detallePedido = new ArrayList<PojoFactura>();
        PojoFactura PedidoHallado;

        for (int i = 0; i < tblProductos.getRowCount(); i++) {

            String Descripcion = tblProductos.getValueAt(i, 1).toString();
            Integer Cantidad = Integer.valueOf(tblProductos.getValueAt(i, 9).toString());
            Double SubTotal = Double.valueOf(tblProductos.getValueAt(i, 10).toString());
            Double TotalPagar = Double.valueOf(txtTotalPagar.getText());
            Double Efectivo = Double.valueOf(txtPaga.getText());
            Double Vuelto = Double.valueOf(txtCambio.getText());

            PedidoHallado
                    = new PojoFactura(Descripcion, Cantidad, SubTotal, TotalPagar, Efectivo, Vuelto);
            detallePedido.add(PedidoHallado);
        }

        return detallePedido;
    }

    private void limpiar() {
        txtNoSerie.setText("");
        cbxTipo.setSelectedIndex(0);
        txtFechaRegistro.setText("");
        txtNITCliente.setText("");
        txtNombreCliente.setText("");
        txtDescuento.setText("");
        txtTotalPagar.setText("");
        txtPaga.setText("");
        txtCambio.setText("");
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        model.setRowCount(0); //eliminar filas existentes
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCrearVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCrearVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCrearVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCrearVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCrearVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProv;
    private javax.swing.JButton btnAplicarDescuento;
    private javax.swing.JButton btnCancelarCompra;
    private javax.swing.JButton btnCrearCompra;
    private javax.swing.JButton btnEliminarFila;
    private javax.swing.JButton btnRegresarCompra;
    private javax.swing.JButton btnSeleccionarProd;
    private javax.swing.JButton btnSeleccionarProv;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JPanel jPnlFactura;
    private javax.swing.JPanel jPnlProductos;
    private javax.swing.JPanel jPnlProveedor;
    private javax.swing.JPanel jPnlUsuario;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblFechaRegistro;
    private javax.swing.JLabel lblNITCliente;
    private javax.swing.JLabel lblNITUsuario;
    private javax.swing.JLabel lblNoSerie;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblPaga;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTotalPagar;
    private javax.swing.JPanel pnlLeft;
    public static javax.swing.JTable tblProductos;
    public static javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtFechaRegistro;
    public static javax.swing.JTextField txtNITCliente;
    public static javax.swing.JTextField txtNITUsuario;
    private javax.swing.JTextField txtNoSerie;
    public static javax.swing.JTextField txtNombreCliente;
    public static javax.swing.JTextField txtNombreUsuario;
    public static javax.swing.JTextField txtPaga;
    public static javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
