package cunori.kardex.views;

import cunori.kardex.controller.UsuarioJpaController;
import cunori.kardex.dao.Usuario;
import java.awt.Color;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JScrollBar;
import javax.swing.JTabbedPane;

/**
 *
 * @author Diego Ramos
 * @author Hermas Ramirez
 */
public class Inicio extends javax.swing.JFrame {
    Integer estadoSet;
    EntityManagerFactory emf;
    UsuarioJpaController UsuarioEntityManager;
    public static String SesionUsuario;
    
    public Inicio() {
        initComponents();
        getContentPane().setBackground(new Color(0, 255, 51));
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/logo.png")).getImage());
        emf = Persistence.createEntityManagerFactory("cunori_kardex_jar_1.0-SNAPSHOTPU");
        UsuarioEntityManager = new UsuarioJpaController(emf);
        InicioSecion();
        
        tpnlContenedor.setEnabledAt(0, false);
        tpnlContenedor.setEnabledAt(1, false);
        tpnlContenedor.setEnabledAt(2, false);
        tpnlContenedor.setEnabledAt(3, false);
        tpnlContenedor.setEnabledAt(4, false);
        tpnlContenedor.setEnabledAt(5, false);
        tpnlContenedor.setEnabledAt(6, false);
        tpnlContenedor.setEnabledAt(7, false);

        //Mensajes que se muestran en Inicio seccion de productos 
        String infoListarProducto = "<html><body>En esta seccion podra listar los productos existentes, asi mismo podra filtrar el producto con cualquier atributo</body></html>";
        String infoCrearProducto = "<html><body>En esta seccion podra agregar productos nuevos, tenga en cuenta que no podra repetir codigo de barras y codin.</body></html>";
        String infoEditarProducto = "<html><body>En este apartado podra editar los productos existentes, tenga en cuenta que los cambios que realice se veran reflejados en todo el sistema (Bodega y Farmacias).</html>";

        //Mensaje que se muestra en Inicio seccion de cheques 
        String infoListarCheques = "<html><body>En esta seccion podras visualizar todos los cheques existentes</body></html>";
        String infoCrearCheques = "<html><body>En esta seccion podras crear y listar cheques segun a quien corresponda el pago</body></html>";
        String infoSinPredeclarar = "<html><body>En esta seccion podras listar todos aquellos cheques que estan sin predeclarar</body></html>";
        String infoPendientesCheques = "<html><body>En esta seccion podras listar todos aquellos cheques que estan pendientes por pagar, ten en cuenta que una vez pagado ya no podras editarlo</body></html>";
        String infoPagadoCheques = "<html><body>En esta seccion podras listar todos aquellos cheques pagados, no puedes realizar modificaciones </body></html>";
        String infoCobrado = "<html><body>En esta seccion podras visualizar todos los cheques que ya fue registrado su cobro</body></html>";
        String infoAnuladoCheques = "<html><body>En esta seccion podras listar todos aquellos cheques que estan anulados, ten en cuenta que no puedes borrarlos</body></html>";
        String infoInicio = "<html><body>Este programa fue diseñado con el fin de facilitar el control de traslados de Corporacion Salom S.A</body></html>";
        
        
        //datos del traslado
        String infoCrearTraslado = "<html><body>En esta seccion podras visualizar todos los traslados creados por los administradores de farmacia</body></html>";
        String infoDescargadoTraslado = "<html><body>En esta seccion podras visualizar todos aquellos traslados que el gerente de logistica (Marlin) haya descargado</body></html>";
        String infoCargadoVerificadoTraslado = "<html><body>En esta seccion podras visualizar aquellos traslados que fueron verificados po el gerente de logistica (Marlin)</body></html>";
        String infoRevisadoSistemaTraslado = "<html><body>En este seccion podras visualizar aquellos traslados verificados y autorizados por el gerente de logistica (Marlin)</body></html>";
        String infoRevisionFisicaTraslado = "<html><body>En esta seccion podras visualizar aquellos traslados que ya fueron revisados fisicamente</body></html>";
        String infoEntregadoTraslado = "<html><body>En esta seccion podras visualizar aquellos traslados que ya fueron entregados a las distintas farmacias</body></html>";
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlLeft = new javax.swing.JPanel();
        pnlInicio = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlUsuarios = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlInventario = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        imageAvatar1 = new com.raven.swing.ImageAvatar();
        pnlClientes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlFacturacion = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnlSalirLogin = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnlProveedores = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnlServicios = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tpnlContenedor = new javax.swing.JTabbedPane();
        pnlSeccionInicio = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        lblBienvenida = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblInfoInicio = new javax.swing.JLabel();
        pnlSeccionUsuario = new javax.swing.JPanel();
        pnlTituloSeccionUsuario = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTituloConsultar = new javax.swing.JLabel();
        lblImgConsultar = new javax.swing.JLabel();
        lblInfoConsultar = new javax.swing.JLabel();
        lblConsultar = new javax.swing.JLabel();
        pnlSeccionInventario = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        pnlTituloSeccionInventarios = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblinfoConsulta = new javax.swing.JLabel();
        lblImgConsulta = new javax.swing.JLabel();
        lblTituloConsulta = new javax.swing.JLabel();
        lblConsulta = new javax.swing.JLabel();
        pnlSeccionClientes = new javax.swing.JPanel();
        pnlTituloSeccionClientes = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblImgConsultar1 = new javax.swing.JLabel();
        lblInfoConsultar1 = new javax.swing.JLabel();
        lblTituloConsultar1 = new javax.swing.JLabel();
        lblConsultar1 = new javax.swing.JLabel();
        pnlSeccionProveedores = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        pnlTituloSeccionProveedores = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        lblImgConsultar2 = new javax.swing.JLabel();
        lblInfoConsultar2 = new javax.swing.JLabel();
        lblTituloConsultar2 = new javax.swing.JLabel();
        lblConsultar2 = new javax.swing.JLabel();
        pnlSeccionServicios = new javax.swing.JPanel();
        pnlTituloSeccionServicios = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lblImgVender = new javax.swing.JLabel();
        lblinfoVender = new javax.swing.JLabel();
        lblTituloVender = new javax.swing.JLabel();
        lblVender = new javax.swing.JLabel();
        lblinfoComprar = new javax.swing.JLabel();
        lblImgComprar = new javax.swing.JLabel();
        lblTituloComprar = new javax.swing.JLabel();
        lblComprar = new javax.swing.JLabel();
        lblinfoKardex = new javax.swing.JLabel();
        lblTituloKardex = new javax.swing.JLabel();
        lblImgKardex = new javax.swing.JLabel();
        lblKardex = new javax.swing.JLabel();
        pnlSeccionFacturacion = new javax.swing.JPanel();
        pnlTituloSeccionFacturacion = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        lblImgConsulta1 = new javax.swing.JLabel();
        lblinfoConsulta1 = new javax.swing.JLabel();
        lblTituloConsulta1 = new javax.swing.JLabel();
        lblConsulta1 = new javax.swing.JLabel();
        pnlSeccionSalir = new javax.swing.JPanel();
        lblImgSalirPrograma = new javax.swing.JLabel();
        lblImgSalirLogin = new javax.swing.JLabel();
        lblTituloSalirPrograma = new javax.swing.JLabel();
        lblTituloSalirLogin = new javax.swing.JLabel();
        lblSalirLogin = new javax.swing.JLabel();
        lblSalirPrograma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1230, 712));

        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_1.png"))); // NOI18N
        pnlFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 190, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/head.jpg"))); // NOI18N
        pnlFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 970, 90));

        pnlLeft.setBackground(new java.awt.Color(129, 164, 220));
        pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlInicio.setBackground(new java.awt.Color(129, 164, 220));
        pnlInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlInicio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlInicioMouseMoved(evt);
            }
        });
        pnlInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlInicioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlInicioMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0home_icon-icons.com_73532.png"))); // NOI18N
        jLabel4.setText("  Inicio");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlInicioLayout = new javax.swing.GroupLayout(pnlInicio);
        pnlInicio.setLayout(pnlInicioLayout);
        pnlInicioLayout.setHorizontalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        pnlInicioLayout.setVerticalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlLeft.add(pnlInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 270, 60));

        pnlUsuarios.setBackground(new java.awt.Color(129, 164, 220));
        pnlUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlUsuarios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlUsuariosMouseMoved(evt);
            }
        });
        pnlUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlUsuariosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlUsuariosMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0users_icon-icons.com_73540.png"))); // NOI18N
        jLabel5.setText("  Usuarios");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlUsuariosLayout = new javax.swing.GroupLayout(pnlUsuarios);
        pnlUsuarios.setLayout(pnlUsuariosLayout);
        pnlUsuariosLayout.setHorizontalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        pnlUsuariosLayout.setVerticalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlLeft.add(pnlUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 270, 60));

        pnlInventario.setBackground(new java.awt.Color(129, 164, 220));
        pnlInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlInventario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlInventarioMouseMoved(evt);
            }
        });
        pnlInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlInventarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlInventarioMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0list_products_84195.png"))); // NOI18N
        jLabel6.setText("  Inventario");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlInventarioLayout = new javax.swing.GroupLayout(pnlInventario);
        pnlInventario.setLayout(pnlInventarioLayout);
        pnlInventarioLayout.setHorizontalGroup(
            pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnlInventarioLayout.setVerticalGroup(
            pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlLeft.add(pnlInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 270, 60));

        imageAvatar1.setGradientColor1(new java.awt.Color(51, 51, 255));
        imageAvatar1.setImage(new javax.swing.ImageIcon(getClass().getResource("/usuarioimg.png"))); // NOI18N
        pnlLeft.add(imageAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 140, 120));

        pnlClientes.setBackground(new java.awt.Color(129, 164, 220));
        pnlClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlClientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlClientesMouseMoved(evt);
            }
        });
        pnlClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlClientesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlClientesMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0clients_users_icon_123774.png"))); // NOI18N
        jLabel3.setText("  Clientes");

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlLeft.add(pnlClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 270, 50));

        pnlFacturacion.setBackground(new java.awt.Color(129, 164, 220));
        pnlFacturacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlFacturacion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlFacturacionMouseMoved(evt);
            }
        });
        pnlFacturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlFacturacionMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlFacturacionMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0facturas_icon_188468.png"))); // NOI18N
        jLabel11.setText("  Facturación");

        javax.swing.GroupLayout pnlFacturacionLayout = new javax.swing.GroupLayout(pnlFacturacion);
        pnlFacturacion.setLayout(pnlFacturacionLayout);
        pnlFacturacionLayout.setHorizontalGroup(
            pnlFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFacturacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        pnlFacturacionLayout.setVerticalGroup(
            pnlFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFacturacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlLeft.add(pnlFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 270, 50));

        pnlSalirLogin.setBackground(new java.awt.Color(129, 164, 220));
        pnlSalirLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSalirLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlSalirLoginMouseMoved(evt);
            }
        });
        pnlSalirLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSalirLoginMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSalirLoginMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0logout_3622.png"))); // NOI18N
        jLabel10.setText(" Salir");

        javax.swing.GroupLayout pnlSalirLoginLayout = new javax.swing.GroupLayout(pnlSalirLogin);
        pnlSalirLogin.setLayout(pnlSalirLoginLayout);
        pnlSalirLoginLayout.setHorizontalGroup(
            pnlSalirLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalirLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        pnlSalirLoginLayout.setVerticalGroup(
            pnlSalirLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalirLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlLeft.add(pnlSalirLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 260, 60));

        pnlProveedores.setBackground(new java.awt.Color(129, 164, 220));
        pnlProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlProveedores.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlProveedoresMouseMoved(evt);
            }
        });
        pnlProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlProveedoresMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlProveedoresMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0proveedores_icon_152059.png"))); // NOI18N
        jLabel8.setText("  Proveedores");

        javax.swing.GroupLayout pnlProveedoresLayout = new javax.swing.GroupLayout(pnlProveedores);
        pnlProveedores.setLayout(pnlProveedoresLayout);
        pnlProveedoresLayout.setHorizontalGroup(
            pnlProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        pnlProveedoresLayout.setVerticalGroup(
            pnlProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlLeft.add(pnlProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 270, 50));

        pnlServicios.setBackground(new java.awt.Color(129, 164, 220));
        pnlServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlServicios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlServiciosMouseMoved(evt);
            }
        });
        pnlServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlServiciosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlServiciosMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0services_97606.png"))); // NOI18N
        jLabel9.setText("  Servicios");

        javax.swing.GroupLayout pnlServiciosLayout = new javax.swing.GroupLayout(pnlServicios);
        pnlServicios.setLayout(pnlServiciosLayout);
        pnlServiciosLayout.setHorizontalGroup(
            pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        pnlServiciosLayout.setVerticalGroup(
            pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlLeft.add(pnlServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 270, 50));

        pnlFondo.add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 270, 720));

        pnlSeccionInicio.setBackground(new java.awt.Color(255, 255, 255));
        pnlSeccionInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlSeccionInicio.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, -1));

        lblBienvenida.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        pnlSeccionInicio.add(lblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 370, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0home_icon-icons.com_73532.png"))); // NOI18N
        jLabel7.setText("  Inicio");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionInicio.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 236, 36));

        lblInfoInicio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblInfoInicio.setForeground(new java.awt.Color(153, 153, 153));
        lblInfoInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionInicio.add(lblInfoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 730, 350));

        tpnlContenedor.addTab("tab1", pnlSeccionInicio);

        pnlSeccionUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlSeccionUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlSeccionUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTituloSeccionUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnlTituloSeccionUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTituloSeccionUsuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloSeccionUsuarioMouseMoved(evt);
            }
        });
        pnlTituloSeccionUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTituloSeccionUsuarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlTituloSeccionUsuarioMouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0users_icon-icons.com_73540.png"))); // NOI18N
        jLabel14.setText("  Usuarios");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlTituloSeccionUsuarioLayout = new javax.swing.GroupLayout(pnlTituloSeccionUsuario);
        pnlTituloSeccionUsuario.setLayout(pnlTituloSeccionUsuarioLayout);
        pnlTituloSeccionUsuarioLayout.setHorizontalGroup(
            pnlTituloSeccionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloSeccionUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTituloSeccionUsuarioLayout.setVerticalGroup(
            pnlTituloSeccionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloSeccionUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlSeccionUsuario.add(pnlTituloSeccionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 60));
        pnlSeccionUsuario.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, -1));

        lblTituloConsultar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTituloConsultar.setForeground(new java.awt.Color(153, 153, 153));
        lblTituloConsultar.setText("Consultar");
        lblTituloConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionUsuario.add(lblTituloConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        lblImgConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listar.png"))); // NOI18N
        lblImgConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionUsuario.add(lblImgConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 290, 140));

        lblInfoConsultar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblInfoConsultar.setForeground(new java.awt.Color(153, 153, 153));
        lblInfoConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionUsuario.add(lblInfoConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 260, 150));

        lblConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/separador.png"))); // NOI18N
        lblConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsultarMouseClicked(evt);
            }
        });
        pnlSeccionUsuario.add(lblConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 316, 371));

        tpnlContenedor.addTab("tab2", pnlSeccionUsuario);

        pnlSeccionInventario.setBackground(new java.awt.Color(255, 255, 255));
        pnlSeccionInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlSeccionInventario.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 280, 10));

        pnlTituloSeccionInventarios.setBackground(new java.awt.Color(255, 255, 255));
        pnlTituloSeccionInventarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTituloSeccionInventarios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloSeccionInventariosMouseMoved(evt);
            }
        });
        pnlTituloSeccionInventarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTituloSeccionInventariosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlTituloSeccionInventariosMouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0list_products_84195.png"))); // NOI18N
        jLabel15.setText("Inventario");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlTituloSeccionInventariosLayout = new javax.swing.GroupLayout(pnlTituloSeccionInventarios);
        pnlTituloSeccionInventarios.setLayout(pnlTituloSeccionInventariosLayout);
        pnlTituloSeccionInventariosLayout.setHorizontalGroup(
            pnlTituloSeccionInventariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloSeccionInventariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
        );
        pnlTituloSeccionInventariosLayout.setVerticalGroup(
            pnlTituloSeccionInventariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloSeccionInventariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlSeccionInventario.add(pnlTituloSeccionInventarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 60));

        lblinfoConsulta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblinfoConsulta.setForeground(new java.awt.Color(153, 153, 153));
        lblinfoConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionInventario.add(lblinfoConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 260, 150));

        lblImgConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listar.png"))); // NOI18N
        lblImgConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionInventario.add(lblImgConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 290, 140));

        lblTituloConsulta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTituloConsulta.setForeground(new java.awt.Color(153, 153, 153));
        lblTituloConsulta.setText("Consulta");
        lblTituloConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionInventario.add(lblTituloConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        lblConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/separador.png"))); // NOI18N
        lblConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsultaMouseClicked(evt);
            }
        });
        pnlSeccionInventario.add(lblConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 316, 371));

        tpnlContenedor.addTab("tab3", pnlSeccionInventario);

        pnlSeccionClientes.setBackground(new java.awt.Color(255, 255, 255));
        pnlSeccionClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTituloSeccionClientes.setBackground(new java.awt.Color(255, 255, 255));
        pnlTituloSeccionClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTituloSeccionClientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloSeccionClientesMouseMoved(evt);
            }
        });
        pnlTituloSeccionClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTituloSeccionClientesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlTituloSeccionClientesMouseExited(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0clients_users_icon_123774.png"))); // NOI18N
        jLabel17.setText("Clientes");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel20.setText("jLabel20");

        javax.swing.GroupLayout pnlTituloSeccionClientesLayout = new javax.swing.GroupLayout(pnlTituloSeccionClientes);
        pnlTituloSeccionClientes.setLayout(pnlTituloSeccionClientesLayout);
        pnlTituloSeccionClientesLayout.setHorizontalGroup(
            pnlTituloSeccionClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloSeccionClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloSeccionClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlTituloSeccionClientesLayout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 62, Short.MAX_VALUE))))
            .addGroup(pnlTituloSeccionClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTituloSeccionClientesLayout.createSequentialGroup()
                    .addGap(0, 130, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 130, Short.MAX_VALUE)))
        );
        pnlTituloSeccionClientesLayout.setVerticalGroup(
            pnlTituloSeccionClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloSeccionClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlTituloSeccionClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTituloSeccionClientesLayout.createSequentialGroup()
                    .addGap(0, 30, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 30, Short.MAX_VALUE)))
        );

        pnlSeccionClientes.add(pnlTituloSeccionClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 60));

        lblImgConsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listar.png"))); // NOI18N
        lblImgConsultar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionClientes.add(lblImgConsultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 290, 140));

        lblInfoConsultar1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblInfoConsultar1.setForeground(new java.awt.Color(153, 153, 153));
        lblInfoConsultar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionClientes.add(lblInfoConsultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 260, 150));

        lblTituloConsultar1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTituloConsultar1.setForeground(new java.awt.Color(153, 153, 153));
        lblTituloConsultar1.setText("Consultar");
        lblTituloConsultar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionClientes.add(lblTituloConsultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        lblConsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/separador.png"))); // NOI18N
        lblConsultar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConsultar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsultar1MouseClicked(evt);
            }
        });
        pnlSeccionClientes.add(lblConsultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 316, 371));

        tpnlContenedor.addTab("tab4", pnlSeccionClientes);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTituloSeccionProveedores.setBackground(new java.awt.Color(255, 255, 255));
        pnlTituloSeccionProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTituloSeccionProveedores.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloSeccionProveedoresMouseMoved(evt);
            }
        });
        pnlTituloSeccionProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTituloSeccionProveedoresMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlTituloSeccionProveedoresMouseExited(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0proveedores_icon_152059.png"))); // NOI18N
        jLabel21.setText(" Proveedores");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel25.setText("jLabel20");

        javax.swing.GroupLayout pnlTituloSeccionProveedoresLayout = new javax.swing.GroupLayout(pnlTituloSeccionProveedores);
        pnlTituloSeccionProveedores.setLayout(pnlTituloSeccionProveedoresLayout);
        pnlTituloSeccionProveedoresLayout.setHorizontalGroup(
            pnlTituloSeccionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloSeccionProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloSeccionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlTituloSeccionProveedoresLayout.createSequentialGroup()
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 62, Short.MAX_VALUE))))
            .addGroup(pnlTituloSeccionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTituloSeccionProveedoresLayout.createSequentialGroup()
                    .addGap(0, 130, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 130, Short.MAX_VALUE)))
        );
        pnlTituloSeccionProveedoresLayout.setVerticalGroup(
            pnlTituloSeccionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloSeccionProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlTituloSeccionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTituloSeccionProveedoresLayout.createSequentialGroup()
                    .addGap(0, 30, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 30, Short.MAX_VALUE)))
        );

        jPanel8.add(pnlTituloSeccionProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 60));

        lblImgConsultar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listar.png"))); // NOI18N
        lblImgConsultar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(lblImgConsultar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 290, 140));

        lblInfoConsultar2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblInfoConsultar2.setForeground(new java.awt.Color(153, 153, 153));
        lblInfoConsultar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(lblInfoConsultar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 260, 150));

        lblTituloConsultar2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTituloConsultar2.setForeground(new java.awt.Color(153, 153, 153));
        lblTituloConsultar2.setText("Consultar");
        lblTituloConsultar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(lblTituloConsultar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        lblConsultar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/separador.png"))); // NOI18N
        lblConsultar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConsultar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsultar2MouseClicked(evt);
            }
        });
        jPanel8.add(lblConsultar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 316, 371));

        javax.swing.GroupLayout pnlSeccionProveedoresLayout = new javax.swing.GroupLayout(pnlSeccionProveedores);
        pnlSeccionProveedores.setLayout(pnlSeccionProveedoresLayout);
        pnlSeccionProveedoresLayout.setHorizontalGroup(
            pnlSeccionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        pnlSeccionProveedoresLayout.setVerticalGroup(
            pnlSeccionProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );

        tpnlContenedor.addTab("tab5", pnlSeccionProveedores);

        pnlSeccionServicios.setBackground(new java.awt.Color(255, 255, 255));
        pnlSeccionServicios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTituloSeccionServicios.setBackground(new java.awt.Color(255, 255, 255));
        pnlTituloSeccionServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTituloSeccionServicios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloSeccionServiciosMouseMoved(evt);
            }
        });
        pnlTituloSeccionServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTituloSeccionServiciosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlTituloSeccionServiciosMouseExited(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0services_97606.png"))); // NOI18N
        jLabel29.setText("Servicios");
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel30.setText("jLabel20");

        javax.swing.GroupLayout pnlTituloSeccionServiciosLayout = new javax.swing.GroupLayout(pnlTituloSeccionServicios);
        pnlTituloSeccionServicios.setLayout(pnlTituloSeccionServiciosLayout);
        pnlTituloSeccionServiciosLayout.setHorizontalGroup(
            pnlTituloSeccionServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloSeccionServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloSeccionServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jSeparator5)))
            .addGroup(pnlTituloSeccionServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTituloSeccionServiciosLayout.createSequentialGroup()
                    .addGap(0, 130, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 130, Short.MAX_VALUE)))
        );
        pnlTituloSeccionServiciosLayout.setVerticalGroup(
            pnlTituloSeccionServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloSeccionServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlTituloSeccionServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTituloSeccionServiciosLayout.createSequentialGroup()
                    .addGap(0, 30, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 30, Short.MAX_VALUE)))
        );

        pnlSeccionServicios.add(pnlTituloSeccionServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 60));

        lblImgVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listar.png"))); // NOI18N
        lblImgVender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionServicios.add(lblImgVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 240, 110));

        lblinfoVender.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblinfoVender.setForeground(new java.awt.Color(153, 153, 153));
        lblinfoVender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionServicios.add(lblinfoVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 210, 160));

        lblTituloVender.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTituloVender.setForeground(new java.awt.Color(153, 153, 153));
        lblTituloVender.setText("Vender");
        lblTituloVender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionServicios.add(lblTituloVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 90, -1));

        lblVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/separador.png"))); // NOI18N
        lblVender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVenderMouseClicked(evt);
            }
        });
        pnlSeccionServicios.add(lblVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 270, 340));

        lblinfoComprar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblinfoComprar.setForeground(new java.awt.Color(153, 153, 153));
        lblinfoComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionServicios.add(lblinfoComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 210, 160));

        lblImgComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listar.png"))); // NOI18N
        lblImgComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionServicios.add(lblImgComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 240, 110));

        lblTituloComprar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTituloComprar.setForeground(new java.awt.Color(153, 153, 153));
        lblTituloComprar.setText("Comprar");
        lblTituloComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionServicios.add(lblTituloComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 100, -1));

        lblComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/separador.png"))); // NOI18N
        lblComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblComprarMouseClicked(evt);
            }
        });
        pnlSeccionServicios.add(lblComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 270, 340));

        lblinfoKardex.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblinfoKardex.setForeground(new java.awt.Color(153, 153, 153));
        lblinfoKardex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionServicios.add(lblinfoKardex, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 210, 160));

        lblTituloKardex.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTituloKardex.setForeground(new java.awt.Color(153, 153, 153));
        lblTituloKardex.setText("Kardex");
        lblTituloKardex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionServicios.add(lblTituloKardex, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 100, -1));

        lblImgKardex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listar.png"))); // NOI18N
        lblImgKardex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionServicios.add(lblImgKardex, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 240, 110));

        lblKardex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/separador.png"))); // NOI18N
        lblKardex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKardex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKardexMouseClicked(evt);
            }
        });
        pnlSeccionServicios.add(lblKardex, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 270, 340));

        tpnlContenedor.addTab("tab6", pnlSeccionServicios);

        pnlSeccionFacturacion.setBackground(new java.awt.Color(255, 255, 255));
        pnlSeccionFacturacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTituloSeccionFacturacion.setBackground(new java.awt.Color(255, 255, 255));
        pnlTituloSeccionFacturacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTituloSeccionFacturacion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTituloSeccionFacturacionMouseMoved(evt);
            }
        });
        pnlTituloSeccionFacturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTituloSeccionFacturacionMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlTituloSeccionFacturacionMouseExited(evt);
            }
        });

        jLabel61.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0facturas_icon_188468.png"))); // NOI18N
        jLabel61.setText("Facturación");
        jLabel61.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel62.setText("jLabel20");

        javax.swing.GroupLayout pnlTituloSeccionFacturacionLayout = new javax.swing.GroupLayout(pnlTituloSeccionFacturacion);
        pnlTituloSeccionFacturacion.setLayout(pnlTituloSeccionFacturacionLayout);
        pnlTituloSeccionFacturacionLayout.setHorizontalGroup(
            pnlTituloSeccionFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloSeccionFacturacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloSeccionFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel61, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jSeparator7)))
            .addGroup(pnlTituloSeccionFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTituloSeccionFacturacionLayout.createSequentialGroup()
                    .addGap(0, 130, Short.MAX_VALUE)
                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 130, Short.MAX_VALUE)))
        );
        pnlTituloSeccionFacturacionLayout.setVerticalGroup(
            pnlTituloSeccionFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloSeccionFacturacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel61, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlTituloSeccionFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTituloSeccionFacturacionLayout.createSequentialGroup()
                    .addGap(0, 30, Short.MAX_VALUE)
                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 30, Short.MAX_VALUE)))
        );

        pnlSeccionFacturacion.add(pnlTituloSeccionFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 60));

        lblImgConsulta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listar.png"))); // NOI18N
        lblImgConsulta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionFacturacion.add(lblImgConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 290, 140));

        lblinfoConsulta1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblinfoConsulta1.setForeground(new java.awt.Color(153, 153, 153));
        lblinfoConsulta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionFacturacion.add(lblinfoConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 260, 150));

        lblTituloConsulta1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTituloConsulta1.setForeground(new java.awt.Color(153, 153, 153));
        lblTituloConsulta1.setText("Consulta");
        lblTituloConsulta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionFacturacion.add(lblTituloConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        lblConsulta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/separador.png"))); // NOI18N
        lblConsulta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConsulta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsulta1MouseClicked(evt);
            }
        });
        pnlSeccionFacturacion.add(lblConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 316, 371));

        tpnlContenedor.addTab("tab7", pnlSeccionFacturacion);

        pnlSeccionSalir.setBackground(new java.awt.Color(255, 255, 255));
        pnlSeccionSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImgSalirPrograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listar.png"))); // NOI18N
        lblImgSalirPrograma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionSalir.add(lblImgSalirPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 200, 80));

        lblImgSalirLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listar.png"))); // NOI18N
        lblImgSalirLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionSalir.add(lblImgSalirLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 210, 80));

        lblTituloSalirPrograma.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTituloSalirPrograma.setForeground(new java.awt.Color(153, 153, 153));
        lblTituloSalirPrograma.setText("Salir del Programa");
        lblTituloSalirPrograma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionSalir.add(lblTituloSalirPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        lblTituloSalirLogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTituloSalirLogin.setForeground(new java.awt.Color(153, 153, 153));
        lblTituloSalirLogin.setText("Salir al Login");
        lblTituloSalirLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSeccionSalir.add(lblTituloSalirLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        lblSalirLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/separador.png"))); // NOI18N
        lblSalirLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalirLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirLoginMouseClicked(evt);
            }
        });
        pnlSeccionSalir.add(lblSalirLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 230, 380));

        lblSalirPrograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/separador.png"))); // NOI18N
        lblSalirPrograma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalirPrograma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirProgramaMouseClicked(evt);
            }
        });
        pnlSeccionSalir.add(lblSalirPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 230, 380));

        tpnlContenedor.addTab("tab8", pnlSeccionSalir);

        pnlFondo.add(tpnlContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 970, 650));
        tpnlContenedor.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInicioMouseClicked
        tpnlContenedor.setSelectedIndex(0);

    }//GEN-LAST:event_pnlInicioMouseClicked

    private void pnlInicioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInicioMouseMoved
        pnlInicio.setBackground(new Color(166, 173, 217));
    }//GEN-LAST:event_pnlInicioMouseMoved

    private void pnlInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInicioMouseExited
        pnlInicio.setBackground(new Color(129, 164, 220));

    }//GEN-LAST:event_pnlInicioMouseExited

    private void pnlUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUsuariosMouseClicked
        tpnlContenedor.setSelectedIndex(1);
    }//GEN-LAST:event_pnlUsuariosMouseClicked

    private void pnlUsuariosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUsuariosMouseMoved
        pnlUsuarios.setBackground(new Color(166, 173, 217));
    }//GEN-LAST:event_pnlUsuariosMouseMoved

    private void pnlUsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUsuariosMouseExited
        pnlUsuarios.setBackground(new Color(129, 164, 220));
    }//GEN-LAST:event_pnlUsuariosMouseExited

    private void pnlInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInventarioMouseClicked
        tpnlContenedor.setSelectedIndex(2);
    }//GEN-LAST:event_pnlInventarioMouseClicked

    private void pnlInventarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInventarioMouseMoved
        pnlInventario.setBackground(new Color(166, 173, 217));
    }//GEN-LAST:event_pnlInventarioMouseMoved

    private void pnlInventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInventarioMouseExited
        pnlInventario.setBackground(new Color(129, 164, 220));
    }//GEN-LAST:event_pnlInventarioMouseExited

    private void pnlTituloSeccionUsuarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSeccionUsuarioMouseMoved
        pnlInicio.setBackground(new Color(166, 173, 217));
    }//GEN-LAST:event_pnlTituloSeccionUsuarioMouseMoved

    private void pnlTituloSeccionUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSeccionUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloSeccionUsuarioMouseClicked

    private void pnlTituloSeccionUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSeccionUsuarioMouseExited
        pnlInicio.setBackground(new Color(129, 164, 220));
    }//GEN-LAST:event_pnlTituloSeccionUsuarioMouseExited

    private void pnlTituloSeccionInventariosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSeccionInventariosMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloSeccionInventariosMouseMoved

    private void pnlTituloSeccionInventariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSeccionInventariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloSeccionInventariosMouseClicked

    private void pnlTituloSeccionInventariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSeccionInventariosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloSeccionInventariosMouseExited

    private void pnlTituloSeccionClientesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSeccionClientesMouseMoved

    }//GEN-LAST:event_pnlTituloSeccionClientesMouseMoved

    private void pnlTituloSeccionClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSeccionClientesMouseClicked

    }//GEN-LAST:event_pnlTituloSeccionClientesMouseClicked

    private void pnlTituloSeccionClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSeccionClientesMouseExited

    }//GEN-LAST:event_pnlTituloSeccionClientesMouseExited

    private void pnlClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClientesMouseClicked
        tpnlContenedor.setSelectedIndex(3);
    }//GEN-LAST:event_pnlClientesMouseClicked

    private void pnlClientesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClientesMouseMoved
        pnlClientes.setBackground(new Color(166, 173, 217));
    }//GEN-LAST:event_pnlClientesMouseMoved

    private void pnlClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClientesMouseExited
        pnlClientes.setBackground(new Color(129, 164, 220));
    }//GEN-LAST:event_pnlClientesMouseExited

    private void pnlTituloSeccionServiciosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSeccionServiciosMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloSeccionServiciosMouseMoved

    private void pnlTituloSeccionServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSeccionServiciosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloSeccionServiciosMouseClicked

    private void pnlTituloSeccionServiciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSeccionServiciosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloSeccionServiciosMouseExited

    private void pnlTituloSeccionProveedoresMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSeccionProveedoresMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloSeccionProveedoresMouseMoved

    private void pnlTituloSeccionProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSeccionProveedoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloSeccionProveedoresMouseClicked

    private void pnlTituloSeccionProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSeccionProveedoresMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloSeccionProveedoresMouseExited

    private void lblSalirProgramaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirProgramaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblSalirProgramaMouseClicked

    private void lblSalirLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirLoginMouseClicked
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblSalirLoginMouseClicked

    private void pnlTituloSeccionFacturacionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSeccionFacturacionMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloSeccionFacturacionMouseMoved

    private void pnlTituloSeccionFacturacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSeccionFacturacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloSeccionFacturacionMouseClicked

    private void pnlTituloSeccionFacturacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTituloSeccionFacturacionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTituloSeccionFacturacionMouseExited

    private void pnlSalirLoginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSalirLoginMouseMoved
        pnlSalirLogin.setBackground(new Color(166, 173, 217));
    }//GEN-LAST:event_pnlSalirLoginMouseMoved

    private void pnlSalirLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSalirLoginMouseClicked
        tpnlContenedor.setSelectedIndex(7);  
    }//GEN-LAST:event_pnlSalirLoginMouseClicked

    private void pnlSalirLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSalirLoginMouseExited
     pnlSalirLogin.setBackground(new Color(129, 164, 220));
    }//GEN-LAST:event_pnlSalirLoginMouseExited

    private void pnlFacturacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFacturacionMouseExited
       pnlFacturacion.setBackground(new Color(129, 164, 220));
    }//GEN-LAST:event_pnlFacturacionMouseExited

    private void pnlFacturacionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFacturacionMouseMoved
      pnlFacturacion.setBackground(new Color(166, 173, 217));
    }//GEN-LAST:event_pnlFacturacionMouseMoved

    private void pnlFacturacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFacturacionMouseClicked
     tpnlContenedor.setSelectedIndex(6);   
    }//GEN-LAST:event_pnlFacturacionMouseClicked

    private void lblConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultarMouseClicked
     ListarUsuarios lu = new ListarUsuarios();
     lu.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_lblConsultarMouseClicked

    private void lblConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultaMouseClicked
     ListarInventario li = new ListarInventario();
     li.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_lblConsultaMouseClicked

    private void pnlProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlProveedoresMouseClicked
        tpnlContenedor.setSelectedIndex(4);
    }//GEN-LAST:event_pnlProveedoresMouseClicked

    private void pnlProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlProveedoresMouseExited
        pnlProveedores.setBackground(new Color(129, 164, 220));
    }//GEN-LAST:event_pnlProveedoresMouseExited

    private void pnlProveedoresMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlProveedoresMouseMoved
        pnlProveedores.setBackground(new Color(166, 173, 217));
    }//GEN-LAST:event_pnlProveedoresMouseMoved

    private void lblConsultar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultar1MouseClicked
        ListarClientes lc = new ListarClientes();
        lc.setVisible(true);
        this.dispose();
                
    }//GEN-LAST:event_lblConsultar1MouseClicked

    private void lblConsultar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultar2MouseClicked
        ListarProveedores lp = new ListarProveedores();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblConsultar2MouseClicked

    private void lblVenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVenderMouseClicked
        FormCrearVenta2 cV = new FormCrearVenta2();
        cV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblVenderMouseClicked

    private void lblComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComprarMouseClicked
        FormCrearCompra cC = new FormCrearCompra();
        cC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblComprarMouseClicked

    private void lblConsulta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsulta1MouseClicked
     ListarFacturacion lf = new ListarFacturacion();
     lf.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_lblConsulta1MouseClicked

    private void pnlServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlServiciosMouseClicked
        tpnlContenedor.setSelectedIndex(5);
    }//GEN-LAST:event_pnlServiciosMouseClicked

    private void pnlServiciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlServiciosMouseExited
        pnlServicios.setBackground(new Color(129, 164, 220));
    }//GEN-LAST:event_pnlServiciosMouseExited

    private void pnlServiciosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlServiciosMouseMoved
        pnlServicios.setBackground(new Color(166, 173, 217));
    }//GEN-LAST:event_pnlServiciosMouseMoved

    private void lblKardexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKardexMouseClicked
        KardexPEPS kp = new KardexPEPS();
        kp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblKardexMouseClicked

    public void InicioSecion(){
        System.out.println("id usuario "+Login.idUsuario);
    SesionUsuario = Login.idUsuario;    
    Usuario usuario =  UsuarioEntityManager.findUsuario(Login.idUsuario);    
    lblBienvenida.setText("Bienvenido "+usuario.getNombre()+" "+usuario.getApellidos());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.ImageAvatar imageAvatar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    public static javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblComprar;
    private javax.swing.JLabel lblConsulta;
    private javax.swing.JLabel lblConsulta1;
    private javax.swing.JLabel lblConsultar;
    private javax.swing.JLabel lblConsultar1;
    private javax.swing.JLabel lblConsultar2;
    private javax.swing.JLabel lblImgComprar;
    private javax.swing.JLabel lblImgConsulta;
    private javax.swing.JLabel lblImgConsulta1;
    private javax.swing.JLabel lblImgConsultar;
    private javax.swing.JLabel lblImgConsultar1;
    private javax.swing.JLabel lblImgConsultar2;
    private javax.swing.JLabel lblImgKardex;
    private javax.swing.JLabel lblImgSalirLogin;
    private javax.swing.JLabel lblImgSalirPrograma;
    private javax.swing.JLabel lblImgVender;
    private javax.swing.JLabel lblInfoConsultar;
    private javax.swing.JLabel lblInfoConsultar1;
    private javax.swing.JLabel lblInfoConsultar2;
    private javax.swing.JLabel lblInfoInicio;
    private javax.swing.JLabel lblKardex;
    private javax.swing.JLabel lblSalirLogin;
    private javax.swing.JLabel lblSalirPrograma;
    private javax.swing.JLabel lblTituloComprar;
    private javax.swing.JLabel lblTituloConsulta;
    private javax.swing.JLabel lblTituloConsulta1;
    private javax.swing.JLabel lblTituloConsultar;
    private javax.swing.JLabel lblTituloConsultar1;
    private javax.swing.JLabel lblTituloConsultar2;
    private javax.swing.JLabel lblTituloKardex;
    private javax.swing.JLabel lblTituloSalirLogin;
    private javax.swing.JLabel lblTituloSalirPrograma;
    private javax.swing.JLabel lblTituloVender;
    private javax.swing.JLabel lblVender;
    private javax.swing.JLabel lblinfoComprar;
    private javax.swing.JLabel lblinfoConsulta;
    private javax.swing.JLabel lblinfoConsulta1;
    private javax.swing.JLabel lblinfoKardex;
    private javax.swing.JLabel lblinfoVender;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlFacturacion;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlInicio;
    private javax.swing.JPanel pnlInventario;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlProveedores;
    private javax.swing.JPanel pnlSalirLogin;
    private javax.swing.JPanel pnlSeccionClientes;
    private javax.swing.JPanel pnlSeccionFacturacion;
    private javax.swing.JPanel pnlSeccionInicio;
    private javax.swing.JPanel pnlSeccionInventario;
    private javax.swing.JPanel pnlSeccionProveedores;
    private javax.swing.JPanel pnlSeccionSalir;
    private javax.swing.JPanel pnlSeccionServicios;
    private javax.swing.JPanel pnlSeccionUsuario;
    private javax.swing.JPanel pnlServicios;
    private javax.swing.JPanel pnlTituloSeccionClientes;
    private javax.swing.JPanel pnlTituloSeccionFacturacion;
    private javax.swing.JPanel pnlTituloSeccionInventarios;
    private javax.swing.JPanel pnlTituloSeccionProveedores;
    private javax.swing.JPanel pnlTituloSeccionServicios;
    private javax.swing.JPanel pnlTituloSeccionUsuario;
    private javax.swing.JPanel pnlUsuarios;
    private javax.swing.JTabbedPane tpnlContenedor;
    // End of variables declaration//GEN-END:variables
}
